import re

# Common packer signatures
PACKER_SIGNATURES = [
    {
        "name": "UPX",
        "pattern": rb"UPX!",
        "type": "Packer",
        "description": "The Ultimate Packer for eXecutables - commonly used for both legitimate and malicious purposes."
    },
    {
        "name": "Themida",
        "pattern": rb"Themida",
        "type": "Protector",
        "description": "Advanced commercial protector with code virtualization and anti-debugging."
    },
    {
        "name": "VMProtect",
        "pattern": rb"VMProtect",
        "type": "Protector",
        "description": "Powerful protector that virtualizes code to prevent reverse engineering."
    },
    {
        "name": "ASPack",
        "pattern": rb"ASPack",
        "type": "Packer",
        "description": "Old but common Windows executable compressor."
    },
    {
        "name": "Enigma",
        "pattern": rb"Enigma Protector",
        "type": "Protector",
        "description": "Software protection and licensing system."
    }
]

# Common library signatures (simplified)
LIBRARY_SIGNATURES = [
    {
        "name": "Microsoft Visual C++",
        "pattern": rb"Microsoft Visual C\+\+ Runtime Library",
        "type": "Compiler",
        "description": "Compiled with MSVC."
    },
    {
        "name": "Go Compiler",
        "pattern": rb"Go build ID:",
        "type": "Compiler",
        "description": "Binary compiled using the Go programming language."
    },
    {
        "name": "Python Installer",
        "pattern": rb"PyInstaller",
        "type": "Installer",
        "description": "Self-extracting Python executable generated by PyInstaller."
    }
]

def scan_binary(file_path):
    findings = []
    try:
        with open(file_path, 'rb') as f:
            content = f.read()
            
            for sig in PACKER_SIGNATURES:
                if re.search(sig["pattern"], content):
                    findings.append(sig)
            
            for sig in LIBRARY_SIGNATURES:
                if re.search(sig["pattern"], content):
                    findings.append(sig)
    except Exception as e:
        pass
    return findings

if __name__ == "__main__":
    import sys
    import json
    if len(sys.argv) > 1:
        print(json.dumps(scan_binary(sys.argv[1]), indent=2))
